---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: create ec2 for web02 server
      amazon.aws.ec2_instance:
        name: web02
        key_name: "devops-key"
        region: "{{region}}"
        vpc_subnet_id: "{{subnet-0204105b84cd54866}}"
        instance_type: t2.micro
        security_group: "sg-0d687f254bd428569"
        network:
          # assign_public_ip: true
          delete_on_termination: true
        image_id: "{{bastion_ami}}"
        tags:
          project: devops
          owner: asif
        wait: true
        wait_timeout: 300
      register: web02_ec2_out
      until: "web02_ec2_out.instance.state.status == 'running' and web02_ec2_out.instance.state.system_status.status == 'ok' and web02_ec2_out.instance.state.instance_status.status == 'ok'"
      retries: 30
      delay: 10