---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: import outpur_var variable
      include_vars: vars/output_vars
    
    - name: Setup ELB for web server
      amazon.aws.elb_classic_lb:
        name: "devops-ELB"
        state: present
        region: "us-east-2"
        # zones:
        #   - "{{zone1}}"
        #   - "{{zone2}}"
        cross_az_load_balancing : true
        instance_ids:
          # - "{{web01_ec2_out_id}}"
          # - "{{web02_ec2_out_id}}"
          - "i-03f351c04414a5a6e"
          - "i-066812c11c9a6eeab"
        security_group_ids: "sg-007f6293b64e39fd9"
        scheme: internet-facing
        purge_instance_ids: true
        stickiness:
          - enabled 
        subnets:
          - "subnet-0c795a5ccb35a7b7b"
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
        health_check:
            ping_protocol: http # options are http, https, ssl, tcp
            ping_port: 80
            ping_path: "/index.html" # not required for tcp or ssl
            response_timeout: 5 # seconds
            interval: 30 # seconds
            unhealthy_threshold: 2
            healthy_threshold: 10
        wait: true
        wait_timeout: 300
        tags:
          project: devops