---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: import outpur_var variable
      include_vars: vars/output_vars
    
    - name: Create Target Group for Devop-ELB
      community.aws.elb_target_group:
        name: Devop-TG
        protocol: http
        region: us-east-2
        port: 80
        vpc_id: vpc-03b60bcb73c20dab9
        health_check_protocol: http
        health_check_path: /
        successful_response_codes: "200,250-260"
        target_type: "instance"
        targets:
          - Id: i-0c397c9b7a19ec456
            Port: 80
        state: present
        wait_timeout: 200
        wait: True
        tags:
          Project: devops


    - name: Setup ELB for web server
      amazon.aws.elb_application_lb:
        name: Devops-ELB
        ip_address_type: "ipv4"
        region: us-east-2
        # vpc_id: vpc-03b60bcb73c20dab9
        security_groups:
          - "sg-0d687f254bd428569"
        subnets:
          - subnet-0204105b84cd54866
          - subnet-0c131de78d9f73937
        listeners:
          - DefaultActions:
            - TargetGroupArn: "arn:aws:elasticloadbalancing:us-east-2:815569990111:targetgroup/Devop-TG/d548051753c82041"
              TargetGroupName: "Devop-TG"
              Type: "instance"
            Port: 80
            Protocol: "http"
        wait: true

