---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: import outpur_var variable
      include_vars: vars/output_vars
    
    - name: import outpur_var variable
      include_vars: vars/output_vars