- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: import vpc variable
      include_vars: vars/vpc_setup

    - name: create vprofile vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        dns_hostnames: true
        dns_support: true
        region: "{{region}}"
        state: "{{state}}"
        tenancy: default
      register: vpc_out

    - debug:
        var: vpc_out