- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: import vpc variable
      include_vars: vars/vpc_setup

    - name: create vprofile vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        dns_hostnames: true
        dns_support: true
        region: "{{region}}"
        state: "{{state}}"
        tenancy: default
      register: vpc_out

    # - debug:
    #     var: vpc_out

    - name: create Public sebnet 1 for zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    - name: create Public sebnet 2 for zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PubSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: create Public sebnet 3 for zone1
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PubSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsub3_out